### ISSUE TITLE
Add dependencies on the README file

### ISSUE THREAD

**Issue by ademcan** [cyber-republic/elastos-ReactNative-framework#9]
If users are not aware of the node version they should use, the "react-native link" command returns the following error:

$[PATH_TO_REPO]/elastos-ReactNative-framework/node_modules/react-native/local-cli/server/checkNodeVersion.js:43
    );
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ($[PATH_TO_REPO]/elastos-ReactNative-framework/node_modules/react-native/local-cli/cli.js:17:1)
    at Module._compile (module.js:541:32)

It is not very informative. One needs to open the checkNodeVersion.js file to see that the required node version is => 8.0. It would be helpful to add a dependency list on the README file.

**Comment by liyangwood** [comment]
thanks, point out the node version in package.json

**Comment by tomsej** [comment]
Think it is better to have dependency in package.json. Is the information about node version in README.md still needed or can we close the issue? @ademcan @liyangwood

**Comment by ademcan** [comment]
I agree (as it's not an external dependency). The package.json was not updated but now it's done, so we can just close this issue I guess

**Comment by tomsej** [comment]
Thanks @ademcan.
